### ISSUE TITLE
Shuffling

### ISSUE THREAD

**Issue by milfordn** [cs361fall2017/team25#1]
Card: As a player, I want to be able to shuffle the deck at the start of the game so that I may have a unique experience with every new game.

Conversation:
- Should produce a different order of random cards every time

Confirmation
- Print and/or compare all cards in order

**Comment by milfordn** [comment]
Assign Paul to this, he is currently not in the CS361 organization

**Comment by leep3** [comment]
I just finished code for shuffle but didn't push it because of the permission.

Below is my code and I will try to solve permission problem on Monday.

    public void shuffle() {
        // shuffles the deck so that it is random

	public java.util.List<Card> newDeck = new ArrayList<>();
	Random ran = new Random () ;
	int temp ;
	
	for (int i = 52 ; i > 0 ; i--) {
		temp = ran.nextInt(i);
		newDeck.add(deck.get(temp));
		deck.remove(temp);
	}

	deck = newDeck ;
    }

I didn't test it because I don't know which one to compile and execute it to test it.

**Comment by milfordn** [comment]
@leep3 you probably can't commit to your feature branch because you're still not a part of the group. I still can't find you in the "assignees" list. Have you contacted the instructor or TAs?

**Comment by leep3** [comment]
@milfordn 

I am for sure that is the problem. I just connect to TAs so let's see how it goes.

**Comment by milfordn** [comment]
Implemented and works as of 10/12/17, waiting pull request
